monolog:
    channels:
        - deprecation # Deprecations are logged in the dedicated "deprecation" channel when it exists
        - tasks # Task execution logging

    handlers:
        main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            channels: ["!event", "!doctrine", "!console", "!deprecation", "!cache", "!request", "!mailer", "!tasks", "!messenger"]
        tasks:
            type: stream
            path: "%kernel.logs_dir%/tasks.log"
            level: debug
            channels: ["tasks"]
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine", "!console", "!deprecation", "!cache", "!request", "!mailer", "!tasks", "!messenger"]
        error_email:
            type: symfony_mailer
            from_email: '%env(EMAIL_NO_REPLY)%'
            to_email: '%env(EMAIL_DEV_TEAM)%'
            subject: 'Critical Application Error in Symfony Scheduler'
            level: critical
            channels: ["!tasks"]  # Don't email task-related errors
