services:
  nginx:
    container_name: nginx
    build:
      context: nginx
      dockerfile: Dockerfile

    ports:
      - "8080:80"

    stdin_open: true
    tty: true

    volumes:
      - ../public:/usr/share/nginx/html/

    extra_hosts:
      - host.docker.internal:host-gateway

  php:
    container_name: php
    build:
      context: php
      dockerfile: Dockerfile
      args:
        # Must match SCHEDULE_RESTART_FILE environment variable below
        SCHEDULE_RESTART_FILE: "/tmp/symfony/schedule-last-updated.dat"

    env_file:
      - mariadb/envVars.public
      - php/envVars.public

    environment:
      # Must match SCHEDULE_RESTART_FILE build arg above
      SCHEDULE_RESTART_FILE: "/tmp/symfony/schedule-last-updated.dat"

    ports:
      - "9000:9000"

    stdin_open: true
    tty: true

    volumes:
      - ..:/var/www
      - /var/log/symfony/symfony-scheduler:/var/log/symfony

    extra_hosts:
      - host.docker.internal:host-gateway

    secrets:
      - app_secrets
      - mariadb_password

  mariadb:
    container_name: mariadb
    build:
      context: mariadb
      dockerfile: Dockerfile

    env_file:
      - mariadb/envVars.public

    ports:
      - "3380:3306"

    stdin_open: true
    tty: true

    volumes:
      - mariadb-data:/var/lib/mariadb

    secrets:
      - mariadb_password
      - mariadb_root_password

    environment:
      MARIADB_PASSWORD_FILE: /run/secrets/mariadb_password
      MARIADB_ROOT_PASSWORD_FILE: /run/secrets/mariadb_root_password

  mail:
    image: reachfive/fake-smtp-server
    ports:
      - "1080:1080"
      - "25:25"
    command: ["node", "index.js", "--smtp-port", "25"]
    restart: unless-stopped

volumes:
  mariadb-data:

secrets:
  app_secrets:
    file: php/appEnvVars.private
  mariadb_password:
    file: mariadb/mariadb_password_file.private
  mariadb_root_password:
    file: mariadb/mariadb_root_password_file.private
